### ISSUE TITLE
[UserStory] Main Class Extension is Missing

### ISSUE THREAD

**Issue by JuliusRoot31** [MetroCS/QualityToolsForBlueJ#10]
# User Story
### Essential components
- [ ] Stakeholder type is identified
- [X] Outcome is described
- [X] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
As a maintainer
I want a class that calls all other needed classes for the Blue J extension that can compile
so that further additions to the project can be run underneath this one class, such as adding to the menu and or being able to interact with BlueJ's editor.

## Acceptance Criteria

* An empty class that compiles
* Follows Blue J's extension template

**Scenario 1**
Given the empty main class extension
when compiled
then no error occurs

## Supporting Information
Blue J's Extension template: https://www.bluej.org/extensions/writingextensions.html

**Comment by jody** [comment]
"developer" is not one of the recognized **stakeholder types**.

Please also provide an explanation of what is meant by "main class".  That phrase is most commonly used to identify a class containing a method with signature `public static void main(String[] args)`.  Why is that a necessary condition for making additions to the project and testing them for later development?
