### ISSUE TITLE
[UserStory] BlueJ Extension Class

### ISSUE THREAD

**Issue by vinsonchin** [MetroCS/QualityToolsForBlueJ#100]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As** a Maintainer  
**I want** the repository to contain source code for a class that extends `bluej.extensions.Extension`  
**so that** I have a basis upon which to build the QT4BJ extension.

## Acceptance Criteria

* Unit tests for the extension class exist in the repository
* An extension class implementation exists in the repository
* The tests and implementation compile without error
* The extension implementation is acknowledged by the BlueJ application and does not cause BlueJ to crash

**Comment by holsappled** [comment]
Team CraftC0ders would like to accept this mission

@holsappled 
@shadycloud 
@SerenaWhite 
@eggsaladsandwch 
@AhmedSamay

**Comment by jody** [comment]
Please feel free to work on this.
I'm keeping this non-exclusive since it affects one of the most immediate milestones.

**Comment by holsappled** [comment]
CraftC0ders is diving into this user story.

Our first task was to locate the Extensions class.  
Following BlueJ's guidance (link below)  we isolated the Extensions class inside the bluejext.jar

 https://www.bluej.org/extensions/writingextensions.html

To fulfill this user story CraftC0ders needs to place the bluejext.jar file into the project and then unpack the .jar file to allow access to the Extensions class.  To do this CraftC0ders will have to make additions to the build (Gradle) and set a compiler classpath to the .jar.  Our group will also develop tests to verify that the .jar exists within the project.  

The end goal of our efforts will be running the script below.  


import bluej.extensions.*;
import bluej.extensions.event.*;
import java.net.URL;

public class SimpleExtension extends Extension {}

**Comment by holsappled** [comment]
CraftC0ders will not  fulfill this acceptance criterion because we do not have an extension to implement

"The extension implementation is acknowledged by the BlueJ application and does not cause BlueJ to crash"

I suggest we create another user story to make

1) simple extension 
2) create a .jar file 
3) put that .jar file into the extensions directory inside BlueJ
4) Then we can see if the BlueJ application will crash and provide a structure for other groups to implement extension tools

HowTo:
https://www.bluej.org/extensions/writingextensions.html

**Comment by jody** [comment]
How you achieve this is internal to your development approach.

The project encourages a test-driven development style. That might include a sequence of steps similar to the following.
1. Create test(s) in accordance with the acceptance criteria, "unit tests for the extension class exist in the repository"
    1. Such tests will fail to compile (at minimum because there is no associated implementation code)
2. Create minimal implementation code that allows error-free compilation of the test class
    1. This involves creating the smallest implementation of a class that extends `bluej.extensions.Extension`
    2. For the implementation class to compile without errors, the `bluej.extensions` package classes must be included in the classpath. Thus the `bluejext.jar` file must appear in the repository and the the source code compilation step of the build process must accommodate that placement.  (Note that there is no need or desire to "unpack" the jar.)
    3. Modify the implementation as necessary for the implementation and test code to compile without error.
3. Verify that the implementation code passes the test(s).
    1. Modify code as necessary to pass the automated test(s).
4. Build the BlueJ extension using the implementation class.
    1. This involves creating a jar file in accordance with the specifications for a [BlueJ extension](https://www.bluej.org/extensions/writingextensions.html).
    2. The build process must afford creation of that jar file configured with the necessary `Main-Class` attribute in its Manifest.
5. Verify that installation of the new extension jar into an instance of the BlueJ application
    1. results in the acknowledgement of BlueJ of that extension, and
    2. that it does not cause the BlueJ application to crash.

**Comment by cjd2951** [comment]
@jody I created a PR for this ticket: https://github.com/MetroCS/QualityToolsForBlueJ/pull/123
If you want to assign it to me and let me see it through.

**Comment by holsappled** [comment]
@jody This user story was solved by @cjd2951
