### ISSUE TITLE
[UserStory] BlueJ Template Reference

### ISSUE THREAD

**Issue by JuliusRoot31** [MetroCS/QualityToolsForBlueJ#102]
# User Story
### Essential components
- [X] Title describes the story
- [X] Stakeholder type is identified
- [X] Outcome is described
- [X] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  maintainer  
**I want**  a reference to the BlueJ Extension Template in the README file
**so that**  additional information can be accessed by other teams 

## Acceptance Criteria

*The link to the BlueJ Extension Template:
 Link: https://www.bluej.org/extensions/writingextensions.html

**Comment by jody** [comment]
Why is more needed than just the following link?
https://www.bluej.org/extensions/writingextensions.html
