### ISSUE TITLE
[UserStory] Integrate CheckStyle into the build 

### ISSUE THREAD

**Issue by yadhikar** [MetroCS/QualityToolsForBlueJ#105]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  Developer 
**I want**  CheckStyle integrated  into the build
**so that**  I  can examine source code and check for coding convention violations.

## Acceptance Criteria
* CheckStyle is Integrated into [build.gradle](build.gradle).

## Supporting Information
  You can find information about the CheckStyle plugin [here](https://docs.gradle.org/current/userguide/checkstyle_plugin.html).
### Dependents
User Story #104

**Comment by yadhikar** [comment]
Please assign this issue to @yadhikar

**Comment by shadycloud** [comment]
Can it be integrated into build.gradle and not build.gradlew? https://stackoverflow.com/questions/39627231/difference-between-using-gradlew-and-gradle

**Comment by jody** [comment]
> Can it be integrated into build.gradle and not build.gradlew? https://stackoverflow.com/questions/39627231/difference-between-using-gradlew-and-gradle

There is no `build.gradlew`.  Can you please clarify your question?

**Comment by yadhikar** [comment]
Can you please reassign this to team hybr-dX @yadhikar @henrykgray @Bitked @MaTTerCuBe

**Comment by Bitked** [comment]
Please assign this issue to @Bitked, my team has it working. It needs review and I want to finish merging if possible.

**Comment by jody** [comment]
> Please assign this issue to @Bitked, my team has it working. It needs review and I want to finish merging if possible.

@Bitked is in the existing set of assignees. No action required; none taken.

**Comment by jody** [comment]
Addressed by PR #157
