### ISSUE TITLE
[UserStory] Integrate JUnit5 into the build, replacing JUnit4.

### ISSUE THREAD

**Issue by Bitked** [MetroCS/QualityToolsForBlueJ#106]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  Developer
**I want** JUnit5 to be integrated into the build, rather than the current JUnit4
**so that**  I can implement unit testing and run test cases for my code with JUnit5.

## Acceptance Criteria
* JUnit5 is integrated using the existing [build.gradle](build.gradle) file.
* JUnit4 is integration is removed/replaced by JUnit5.

## Supporting Information
* The JUnit5 Platform(including JUnit5) Gradle Plugin generates JUnit 4 style XML test reports. These XML files are output to build/test-results/junit-platform by default.

* You can find additional information here at [gradle.org](https://docs.gradle.org/5.2.1/userguide/java_testing.html#using_junit5) on integrating JUnit5 in Gradle.

### Dependents
User story #104

**Comment by Bitked** [comment]
Please assign @Bitked to this issue.

**Comment by jody** [comment]
Please confirm that JUnit is not _already_ integrated into the build.

Also note that the development conventions specify JUnit 5 (not JUnit 4).

**Comment by Bitked** [comment]
Confirmed that JUnit4 is already integrated into the build.
Story updated to reflect switching to JUnit5 from the current JUnit4.
