### ISSUE TITLE
[UserStory] QT4BJ extension has its own panel in BlueJ Preferences>Extensions

### ISSUE THREAD

**Issue by jody** [MetroCS/QualityToolsForBlueJ#112]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  {_user, educator_}  
**I want**  _the Quality Tools for BlueJ extension to have an identified panel in the Extensions tab of the Blue: Preferences window_  
**so that**  _I am aware that the extension is installed and I know where to configure its properties, if any._  

### Scenario 1
**Given**  _A running BlueJ instance with the QT4BJ extension installed_  
**when**  _the Preferences window is opened and the Extensions tab selected_  
**then**  _a panel, named with and used by the extension, is displayed in the Extensions tab_  

### Scenario 2
**Given** _a build of the product jar file_  

**when**
- _the product jar file is copied into a BlueJ application's extensions directory,_
- _the BlueJ application is opened, and_  
- `BlueJ > Preferences > Extensions` _is selected in the BlueJ application_  

**then** _a Quality Tools extension panel displays in the window._

Example:
<img width="798" alt="Screen Shot 2019-11-21 at 7 41 11 AM" src="https://user-images.githubusercontent.com/10522689/69473447-cec98400-0d71-11ea-9e82-2b14c9bbf872.png">

## Supporting Information
Example of a BlueJ Preferences window showing the Extensions tab containing preference panels for three extensions (Submitter, QT4BJ, Checkstyle). The QT4BJ preferences panel includes a meaningless preference item solely to illustrate the desired look and feel.
<img width="800" alt="PreferencesExtensions" src="https://user-images.githubusercontent.com/379845/69016874-de0a9500-095f-11ea-8127-781e2aeab929.png">

### Depends On
User Story #100 
### Dependents
_(Issues dependent on this story)_

**Comment by holsappled** [comment]
#133 CraftC0ders found a bug with the current .jar file.  This will need to be addressed before moving forward with this user story.

**Comment by jody** [comment]
As discussed in person, the bug may be specific to a configuration (possibly just OSX Catalina).

**Comment by holsappled** [comment]
I was able to create the BlueJ Preferences window showing the Extensions tab containing preference panels for Submitter and QT4BJ.  I  added a class to the QualityToolsExtension.java file.  I have a question about CheckStyle.  Do you want me to simply put the .jar from CheckStyle into the BlueJ applications extensions directory?  It seems like cheating.  Implementing the CheckStyle into our QualityToolsForBlueJ.jar is a task worthy of its own user story.(Our group can write)  
I believe we should downgrade this user story to only include the Submitter and QT4BJ and then I can send a pull request for the additions to the QualityToolsExtension.java file.

![image](https://user-images.githubusercontent.com/10522689/69348262-1f869300-0c33-11ea-8aeb-0729d4219ebe.png)

**Comment by jody** [comment]
The user story and the acceptance criteria define what is necessary and sufficient.  No specification indicates the need for any other extensions.

(Perhaps interpretation of the image in "Supporting Information" led to confusion.)

**Comment by holsappled** [comment]
Understood.  
I am in contact with team members @SerenaWhite about reviewing my JUnit tests.  I need to ensure my tests are PR acceptable.  We should hopefully have a pull request tonight.

(Perhaps interpretation of the image in "Supporting Information" led to confusion.)

This was my confusion.

**Comment by shadycloud** [comment]
```# AcceptanceTest for QualityToolsExtension.jar

Due to the difficulty of JUnit tests developers created the following acceptance test to verify the start up functionality of the BlueJ application. 

Is there exactly one and only one acceptance test? Is a new file needed for an additional test?

Is the intent that this only apply to a file named QualityToolsExtension.jar? Does it need to be rewritten or replaced if the name of the jar file evolves during the lifetime of the product?

# Steps 

1) Gradle build the project with JDK version 11
---
2) Copy the QualityToolsExtension.jar into the BlueJ applications extensions directory.
---
3) Open the BlueJ application
---
4) In the BlueJ application select **Help -> Installed Extensions**
	
          -Verify that the Quality Tools Extension displays in the window (see picture below)
<img width="498" alt="Screen Shot 2019-11-22 at 9 33 28 PM" src="https://user-images.githubusercontent.com/10522689/69473441-b78a9680-0d71-11ea-9b22-e54c952c2a1e.png">

---
5) In the BlueJ application select **BlueJ -> Preferences “Extensions Tab”**

          -Verify that the Quality Tools Extension displays in the window (see picture below)
<img width="798" alt="Screen Shot 2019-11-21 at 7 41 11 AM" src="https://user-images.githubusercontent.com/10522689/69473447-cec98400-0d71-11ea-9e82-2b14c9bbf872.png">
```

**Comment by shadycloud** [comment]
# AcceptanceTest for QualityToolsExtension.jar

# Steps 

1) Gradle build the project with JDK version 11, 12, and 13
---
2) Copy the QualityToolsExtension.jar into the BlueJ applications extensions directory.
---
3) Open the BlueJ application
---
4) In the BlueJ application select **Help -> Installed Extensions**
	
          -Verify that the Quality Tools Extension displays in the window (see picture below)
<img width="498" alt="Screen Shot 2019-11-22 at 9 33 28 PM" src="https://user-images.githubusercontent.com/10522689/69473441-b78a9680-0d71-11ea-9b22-e54c952c2a1e.png">

---
5) In the BlueJ application select **BlueJ -> Preferences “Extensions Tab”**

          -Verify that the Quality Tools Extension displays in the window (see picture below)
<img width="798" alt="Screen Shot 2019-11-21 at 7 41 11 AM" src="https://user-images.githubusercontent.com/10522689/69473447-cec98400-0d71-11ea-9e82-2b14c9bbf872.png">

**Comment by AhmedSamay** [comment]
Need to create a new User Story for acceptance testing for the product.

**Comment by jody** [comment]
Updated this User Story's _Acceptance Criteria_ with **Scenario 2**.
