### ISSUE TITLE
[BUG] Library and LibraryTest do not belong in the project

### ISSUE THREAD

**Issue by jody** [MetroCS/QualityToolsForBlueJ#117]
**Describe the bug**
The classes Library and LibraryTest were introduced to verify the installation of Gradle as the project build tool. Both should have been removed after initial investigation and verification.

**To Reproduce**
1. Library.java exists within [src/main/java/edu/msudenver/bluejext/qualitytools](../blob/master/src/main/java/edu/msudenver/bluejext/qualitytools/)
2. LibraryTest.java exists within [src/test/java/edu/msudenver/bluejext/qualitytools](../blob/master/src/test/java/edu/msudenver/bluejext/qualitytools/)

**Expected behavior**
Neither Library nor LibraryTest should appear within the repository.
No references to either should exist within the repository or build process.

**Comment by lnieddu** [comment]
Dr Jody Paul, 

Could you assign this ticket to @lnieddu And @ppanth7 and @LStCyr

**Comment by jody** [comment]
What's up with the delay in simply removing 2 files?

**Comment by lnieddu** [comment]
Dr. Paul,

They have been deleted.

Respectfully,
Lucas Nieddu

**Comment by jody** [comment]
Just needed a reference to when they were deleted.  I think I found it myself in PR #123.
