### ISSUE TITLE
[UserStory] Gradle build file for user written code

### ISSUE THREAD

**Issue by lnieddu** [MetroCS/QualityToolsForBlueJ#128]
# User Story
### Essential components
- [ ] Title describes the story
- [ ] Stakeholder type is identified
- [ ] Outcome is described
- [ ] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a user 
**I want a tutorial of how to add a build file to a simple code 
**so that I can see the important components of a build file as it pertains to my code. 

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_
Rule 1)There is a link to a Gradle information page
Rule 2)There is a drop down menu that shows the user an example build file of the code they have written.
Rule 3) There is a dropdown under tools that lists the positive and negative benefits of using Gradle 

### Scenario 1
**Given**  a user has written a small program
**when**  they click a dropdown menu under their class name  
**then** a build file of the program they have written will appear. 

## Supporting Information
_(Relevant information, context, resources)_

**Comment by jody** [comment]
Out of this project's scope.
