### ISSUE TITLE
[UserStory] Automated .jar file mover

### ISSUE THREAD

**Issue by nateprudhomme** [MetroCS/QualityToolsForBlueJ#130]
# User Story
As a maintainer I would like to see Gradle move a newly created .jar file for a simple extension to the BlueJ extensions folder

### Essential components
- [ ] Title describes the story
- [ ] Stakeholder type is identified
- [ ] Outcome is described
- [ ] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  Maintainer 
**I want**  Gradle to move a newly created .jar from a simple extension into the extensions directory  
**so that**  it won't be necessary for us to locate and move the .jar to the directory ourselves.

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

* _Rule 1_ Must not break BlueJ
* _Rule 2_ Must place the .jar into the correct directory
* _Rule 3_

### Scenario 1
**Given**  a version of BlueJ with Gradle involved
**when**  a new .jar is created for an extension
**then**  Gradle moves it to the extensions directory 

## Supporting Information
_(Relevant information, context, resources)_

### Depends On
_(Issues on which this story depends)_
### Dependents
_(Issues dependent on this story)_

**Comment by jody** [comment]
Please provide more justification regarding the need for this.
(It seems like the action is potentially unique to each user's system, configuration, and preference.)

**Comment by jody** [comment]
Doesn't seem feasible or necessary.
