### ISSUE TITLE
[UserStory]Configure the Java Version Compatability

### ISSUE THREAD

**Issue by LStCyr** [MetroCS/QualityToolsForBlueJ#132]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a** maintainer 
**I want** the source and target compatibility for versions of Java to be specified in the build.gradle for Java 11
**so that** I can enforce Java compatibility with BlueJ

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

* _Rule 1_ I can only build the project using Java 11
* _Rule 2_
* _Rule 3_

### Scenario 1
**Given** I try to run the project 
**when**  with a version of Java that isn't Java 11
**then**  the project build fails

## Supporting Information
_(Relevant information, context, resources)_

### Depends On
_(Issues on which this story depends)_
### Dependents
_(Issues dependent on this story)_

**Comment by jody** [comment]
Unclear why the build should fail for all versions of Java other than 11.  Needs more clear specification of the problem.

In particular, why would a maintainer find it desirable for the build to fail for the current version of Java, Java 12, or later versions of Java?

What is the dependency that needs to be met?  Is there another solution that is more appropriate?

**Comment by jody** [comment]
See bug #136
