### ISSUE TITLE
[BUG] BlueJ Preference window not appearing with QualityToolsForBlueJ.jar

### ISSUE THREAD

**Issue by AhmedSamay** [MetroCS/QualityToolsForBlueJ#133]
**Describe the bug**
After the build with the QualityToolsForBlueJ.jar placed in the BlueJ extensions folder, the Preference window does not open. If QualityToolsForBlueJ.jar is removed the Preference window operates properly.  

**To Reproduce**
1. Go to extensions folder in BlueJ application and place QualityToolsForBlueJ.jar.
2. Open BlueJ application, click on finder, and then Preferences. 
3. See error: window does not display. 

**Expected behavior**
When clicking on Preferences, expect Preference window to appear. 

**Screenshots**
N/A

**Environment Configuration (please complete the following information):**
 - Product Version: [0.0.1]
 - OS: [OS X 1.15.1]
 - IDE: [BlueJ 4.2.2]
 - JDK: [openjdk 13 2019-11-19]

**Smartphone (please complete the following information):**
N/A

**Additional context**
Bug is most likely located inside QualityToolsExtension.java file in src folder when creating QualityToolsForBlueJ.jar.

**Comment by shadycloud** [comment]
Attention: I don't think this is a bug, because I wasn't able to recreate the apparent problem.

**Comment by shadycloud** [comment]
<img width="1218" alt="Screen Shot 2019-11-19 at 7 32 38 PM" src="https://user-images.githubusercontent.com/13189052/69204198-70976980-0b03-11ea-9b95-abb410b145dc.png">

**Comment by holsappled** [comment]
I originally found the error running Catalina "OS update" [OS X 1.15.1].  I still can not see the window.

**Comment by jody** [comment]
We need additional testers to verify that they can reproduce this bug.

**Comment by holsappled** [comment]
After re-installing BlueJ on Catalina OS I am now able to open the Preference window with the QualityToolsForBlueJ.jar in the extensions directory.  
OS: [OS X 1.15.1]
IDE: [BlueJ 4.2.2]

**Comment by jody** [comment]
This bug report seems closable.
Possibly related: Bug #136
