### ISSUE TITLE
[UserStory] Production jar should be named QualityTools.jar

### ISSUE THREAD

**Issue by jody** [MetroCS/QualityToolsForBlueJ#138]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  {_user, educator_}
**I want**  _the root name of the product jar to be QualityTools_  
**so that**  _I have a consistent way to identify the product as approved by the product owner._  

## Acceptance Criteria

* The product jar file is named **QualityTools.jar**

## Related Information
Naming development jar files: #149

**Comment by shadycloud** [comment]
I would like to give my opinion that I think we should include the version number in our file name.

**Comment by jody** [comment]
> my opinion that I think

It would be useful to hear rationales that address the relative merits of (a) restricting the product to only one of the two options in this story, and if so restricted (b) which of the two options is to be adopted.

In terms of matching convention...
- Neither the **BlueJ** _application_ nor the supplied **submitter** _extension_ include the release number in their file names.

- Almost all of the extensions available through the [BlueJ Extensions](https://www.bluej.org/extensions/extensions.html) page do not have a version number in the jar file name.

- Some of the [BlueJ Extensions](https://www.bluej.org/extensions/extensions.html) **do** have release numbers (versions) in their jar file names, including PatternCoder and Checkstyle.

**Comment by shadycloud** [comment]
I am speaking from my experience of linux distros. In my experience, it has been great help to see the version number in the file name.

**Comment by shadycloud** [comment]
<img width="1198" alt="Screen Shot 2019-11-21 at 3 59 10 PM" src="https://user-images.githubusercontent.com/13189052/69383995-58952680-0c78-11ea-99b1-c88d862f52d7.png">

**Comment by shadycloud** [comment]
I got that straight from the BlueJ site.

**Comment by shadycloud** [comment]
Also, <img width="875" alt="Screen Shot 2019-11-21 at 4 08 11 PM" src="https://user-images.githubusercontent.com/13189052/69384302-2b954380-0c79-11ea-99dc-0ff9244f685f.png">

**Comment by shadycloud** [comment]
I think there is something to be adopted from one of the most popular Java extensions including the version number in it's file name. 
<img width="875" alt="Screen Shot 2019-11-21 at 4 08 11 PM" src="https://user-images.githubusercontent.com/13189052/69384452-9181cb00-0c79-11ea-8641-51593007d93d.png">

**Comment by jody** [comment]
> I got that straight from the BlueJ site.
It appears that you may be suggesting that the extension be packaged in a folder and that such folder include the version number in its name.  (That is the case with the BlueJ _application,_ which includes version numbering of the distribution folder, but does not include the version number in the name of the actual product file.)

Please open a new User Story that describes the nature of extension packaging.

**Comment by jody** [comment]
Reduced scope of this user story to naming of  _production_ jars.
Created new user story #149 for naming of _development_ jars.

**Comment by jody** [comment]
Copy/Rename task, **dist**, added to build.gradle
  https://github.com/MetroCS/QualityToolsForBlueJ/blob/99461c267764af028913cec80715cce2e088b6cd/build.gradle#L73-L82
