### ISSUE TITLE
[UserStory] Documentation on how to Integrate OpenClover for Project Build Environment.

### ISSUE THREAD

**Issue by ppanth7** [MetroCS/QualityToolsForBlueJ#142]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [ ] Outcome is described
- [ ] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  Maintainer  
**I want**  Documentation on to Integrate OpenClover 
**so that**  users know how to apply the plugin to the Project Build Environment.

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

* Link to OpenClover
* Requirements and limitations
* Configuration

## Supporting Information
_(Relevant information, context, resources)_

### Depends On
userstory #2

**Comment by jody** [comment]
"How to integrate"?  I'm confused about what this documentation actually addresses.

**Comment by jody** [comment]
The information appears already provided at expected location: [http://openclover.org/doc/manual/4.2.0/gradle--gradle-clover-plugin.html](http://openclover.org/doc/manual/4.2.0/gradle--gradle-clover-plugin.html)

Will consider re-opening if additional justification provided.
