### ISSUE TITLE
[UserStory] Need acceptance test for product. 

### ISSUE THREAD

**Issue by AhmedSamay** [MetroCS/QualityToolsForBlueJ#152]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a** maintainer
**I want** acceptance tests for the product  
**so that** I can verify that QualityToolsExtension.jar is working properly with the BlueJ application.  

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

* _Rule 1_ #112 QT4BJ extension has its own panel in BlueJ. 
* _Rule 2_ QualityToolsExtension.jar does not crash BlueJ application. 
* _Rule 3_ #113 QT4BJ extension appears in "Installed Extensions" window

### Scenario 1
**Given** a gradle build
**when** the build is run  
**then** then QualityToolsExtension.jar will display pass/fail on tests. 

## Supporting Information
_(Relevant information, context, resources)_

### Depends On
_(Issues on which this story depends)_ #112 
### Dependents
_(Issues dependent on this story)_ #149

**Comment by holsappled** [comment]
I worked with #112 and #113 and wanted to share that a clear understanding of how to use the Gradle build and output of the QualityToolsExtension.jar needs to be understood.  BlueJ provides a guide on how we had gotten to this point thus far.  

https://bluej.org/extensions/writingextensions.html

**Comment by jody** [comment]
I'm confused by this User Story, including the _title_ and _story_ (which are non-specific) and the acceptance criteria (which cites user stories as rules and whose scenario is already met by the existing build process).

**Comment by AhmedSamay** [comment]
After discussion with shareholder, found User Story is irrelevant.
