### ISSUE TITLE
[UserStory] Extension Overview

### ISSUE THREAD

**Issue by vlazosar** [MetroCS/QualityToolsForBlueJ#16]
# User Story
### Essential components
- [ ] Stakeholder type is identified
- [ ] Outcome is described
- [ ] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
As a Maintainer
I want a simple report on the benefits of static code analysis
so that Users are persuaded into using the extension.

## Acceptance Criteria
Rules or scenarios are acceptable formats.

* The overview is no longer than 6 sentences.
* Written for an audience with a basic understanding of project development
   i.e. A class of students in CS3250 

**Ideal Scenario**
Given a well-written overview
when a User reads the overview
then the User tries out the extension.
And they love it :green_heart:!!!

**Comment by jody** [comment]
Persuading users doesn't seem an appropriate goal for the "maintainer" stakeholders.
Why is a limit of "static code analysis" placed?  In particular why aren't dynamic code analysis tools part of the extension or the report of benefits?
There appears to be some confusion about "users of the extension", who are presumed to primarily be CS-1 students and those who would be maintaining the product (e.g., students on CS3250).
