### ISSUE TITLE
[UserStory] Add repository link to project Home page

### ISSUE THREAD

**Issue by jody** [MetroCS/QualityToolsForBlueJ#22]
# User Story
### Essential components
- [x] Issue title describes the user story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
As a  {maintainer, system administrator, educator}
I want  the project Home page to have a link to the project repository
so that  I may access information about project status and development effort

## Acceptance Criteria

* The Home page contains a link to the project repository

## Supporting Information
Project Home page: https://metrocs.github.io/QualityToolsForBlueJ/
Project Repository page: https://github.com/MetroCS/QualityToolsForBlueJ

## Dependencies
Supports User Story #20

**Comment by shadycloud** [comment]
@shadycloud --  requesting to be assigned this task.
