### ISSUE TITLE
[UserStory] Select tools for integration

### ISSUE THREAD

**Issue by jody** [MetroCS/QualityToolsForBlueJ#3]
# User Story
### Essential components
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
As an educator
I want a prioritized list of code quality analysis tools
so that developers know which tools are most important to integrate

## Acceptance Criteria
Rules or scenarios are acceptable formats.

- [x] The project documentation lists desirable code quality analysis tools
- [x] The project documentation associates stakeholders' priorities with code quality analysis tools
- [x] The project documentation identifies the desired order of integration of the code quality analysis tools.

**Comment by jody** [comment]
Common tools to consider for inclusion:

* SpotBugs
* PMD
* CPD
* Checkstyle
* JaCoCo

**Comment by JustinSingleton303** [comment]
Codebenders3250 are going to take a look at this issue.

**Comment by JustinSingleton303** [comment]
Codebenders3250 are working on producing code for extensions containing SpotBugs and Checkstyle.

**Comment by jody** [comment]
This is an "epic" and Codebenders3250 seem like they are intending to work on _part_ of this user story.  If that's the case, then there should be a new User Story that addresses just the part intended to be addressed, with cross-citations to indicate the dependency relationship.

The phrase _"working on producing code for"_ isn't clear. What is intended to be produced and when will there be a pull request?  Again, this suggests that the intent isn't to deliver the full result within a week (sprint) timeframe, so greater clarity is needed. 

Also, why "extensions" plural, when the intent is for a **single** extension that integrates multiple tools?

**Comment by jstrelka** [comment]
The following team and its members would like to be assigned to this issue:
@MetroCS/efficientsoftwarehypothesis 
@jstrelka 
@TImmyTurner123 
@BlackCanyonDreams 
@GracchusMinor 
@Dendelime

**Comment by jody** [comment]
Addressed by [toolsForIntegration.md](../blob/master/toolsForIntegration.md)
