### ISSUE TITLE
Assign Issue to team

### ISSUE THREAD

**Issue by ppanth7** [MetroCS/QualityToolsForBlueJ#34]
# User Story
### Essential components
- [ ] Title describes the story
- [ ] Stakeholder type is identified
- [ ] Outcome is described
- [ ] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
As a Professor I want to be able to assign to-do project to team of students. I want an extension in BlueJ that displays the list of to-do projects and students be able to select the project they want to work on, so that they won't have to  make a comment on issue and send me an email to asking to assign the issue.

## Supporting Information
Use GitHub API to get list of issue and see which one are assigned or which one's are not. Create an Bleuj extension that displays the title of an issue in a list view based on the data provided from API. If a team wants to work on the issue they click on the issue from the list, a popup appears that asks for username or team name. When they enter the info and hit send. The extension sends an email with the group name or username with the issue they want to work on. Then Organization assigns the ticket to the group and the tickets that are assigned will be removed from the list in the extension.

**Comment by jody** [comment]
Missing **Acceptance Criteria**.
"Professor" is not one of the identified [stakeholder types](https://github.com/MetroCS/QualityToolsForBlueJ/blob/master/Vision.md).  Was "Educator" intended?  "Maintainer"?

**Supporting Information** section seems to suggest creating a _BlueJ extension_ that interfaces with the _GitHub API_ and a _mail server_.  Requiring use of BlueJ to assign issues within GitHub requires greater inquiry and validation versus other potential approaches.

**Comment by jody** [comment]
Inactive.
