### ISSUE TITLE
Possible BlueJ Extension

### ISSUE THREAD

**Issue by corywilson88** [MetroCS/QualityToolsForBlueJ#35]
As a user, I want to easily switch between "light mode" and "dark mode" so that when I use BlueJ in any enviornment it is easier on my eyes to look at.

Acceptance Criteria:
1. Somewhere in the interface, I can easily toggle between light and dark mode
2. Light mode can be the default them and colors for BlueJ
3. Dark mode must primarily use blacks and greys for backgrounds and have light colors for text

**Comment by jody** [comment]
This appears to be a BlueJ issue, not a Quality Tools for BlueJ extension issue.
