### ISSUE TITLE
Menu Description Extension

### ISSUE THREAD

**Issue by corywilson88** [MetroCS/QualityToolsForBlueJ#36]
As an instructor, I want BlueJ to have menus that describe what each option does explicitly instead of using complicated jargon so that my students can easily understand what they do.

Acceptance Criteria:
1. All of the menus must contain all of the original options
2. Very brief explanation is displayed to the user what each option does
3. No jargon can be used in explanations

**Comment by jody** [comment]
Is there a reason why this user story is restricted to only a subset (Instructor) of the identified stakeholder type (Educator)?

There doesn't seem to be a relevant context for this user story.  Is this intended to be a bug report for the BlueJ application?

**Comment by jody** [comment]
Inactive.
