### ISSUE TITLE
Communication Tool

### ISSUE THREAD

**Issue by corywilson88** [MetroCS/QualityToolsForBlueJ#37]
As an extension developer, I need a place to look for ongoing feedback to the extensions being developed so incremental changes can be approved and the project can keep moving forward.

Acceptance Criteria:
1. Establish what tool is to be used for this communication to happen (i.e. Trello, GitHub, Redmine, etc.)
2. The communication must easily notify the project owner when feedback is desired and notify the developer when feedback is given

**Comment by jody** [comment]
Note that "extension developer" isn't one of the [identified stakeholders](https://github.com/MetroCS/QualityToolsForBlueJ/blob/master/Vision.md).

It appears that the first acceptance criteria is already satisfied via the project being hosted on GitHub, which is one of the options presented.

**Comment by jody** [comment]
Inactive.
