### ISSUE TITLE
Testing Framework

### ISSUE THREAD

**Issue by corywilson88** [MetroCS/QualityToolsForBlueJ#38]
As an extension developer, I want to establish how we will be testing the code so that everyone uses a standard framework.

Acceptance Criteria:
1. Decide on a testing framework to use (JUnit, TestNG, etc.)
2. Choose a metric to see if there is enough test coverage throughout the code

**Comment by jody** [comment]
Note that "**Acceptance Criteria**" are statements (rules) that can be verified in the product.
These fulfill the third "C" (Confirmation) of the "Agile [Thee C's](https://www.agilealliance.org/glossary/three-cs/)" (“Card, Conversation, Confirmation”). 
In this case, _"Choose a style guide,..."_ doesn't provide the means to verify the _outcome._  It seems more like advice to whoever may be working on this issue about _how_ they could work towards creating the desired outcome.  

Also note that "extension developer" isn't one of the [identified stakeholders](https://github.com/MetroCS/QualityToolsForBlueJ/blob/master/Vision.md).

See also:  
https://gouda.msudenver.edu/moodle/mod/url/view.php?id=9950  
https://gouda.msudenver.edu/moodle/mod/url/view.php?id=10025

**Comment by jody** [comment]
Inactive.
