### ISSUE TITLE
Style Guide

### ISSUE THREAD

**Issue by corywilson88** [MetroCS/QualityToolsForBlueJ#39]
As an extension developer, I want an established style guide for the code being written so that all of the code can be uniform and easily read by everyone working on the project.

Acceptance Criteria:
1. Choose a style guide that already exists, create our own, or just follow "conventional" Java rules
2. Create a build environment where the style can be tested to see if it meets the correct criteria

**Comment by jody** [comment]
Note that "**Acceptance Criteria**" are statements (rules) that can be verified in the product.
These fulfill the third "C" (Confirmation) of the "Agile [Thee C's](https://www.agilealliance.org/glossary/three-cs/)" (“Card, Conversation, Confirmation”). 
In this case, _"Choose a style guide,..."_ doesn't provide the means to verify the _outcome._  It seems more like advice to whoever may be working on this issue about _how_ they could work towards creating the desired outcome.  

See also:  
https://gouda.msudenver.edu/moodle/mod/url/view.php?id=9950  
https://gouda.msudenver.edu/moodle/mod/url/view.php?id=10025
