### ISSUE TITLE
[UserStory] define output directory for dependencies and compiled code

### ISSUE THREAD

**Issue by cjd2951** [MetroCS/QualityToolsForBlueJ#41]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [ ] Outcome is described
- [ ] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
As an extension maintainer, I want to define the output directory structure for compiled code/dependencies.

## Acceptance Criteria

* _Rule 1_ Ensure that the project has a configuration specifying the output directory.

**Comment by jody** [comment]
Does not adhere to the user story template; some required information is missing.
