### ISSUE TITLE
[UserStory] define distribution output directory structure

### ISSUE THREAD

**Issue by cjd2951** [MetroCS/QualityToolsForBlueJ#42]
# User Story
### Essential components
- [ ] Title describes the story
- [ ] Stakeholder type is identified
- [ ] Outcome is described
- [ ] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
As an extension maintainer, I want to define the output directory structure for a new distributable of the project.

## Acceptance Criteria
* _Rule 1_ Ensure that the project has a configuration specifying the distribution directory structure.

**Comment by jody** [comment]
Please use the user story template structure to ensure that all aspects are addressed.  There is no rationale for this requirement.  As written, it suggests that each maintainer wishes to be able to specify an output directory structure.

**Comment by jody** [comment]
Clean up.  No recent response.
