### ISSUE TITLE
[UserStory] see if I use all the variables that I declare

### ISSUE THREAD

**Issue by holsappled** [MetroCS/QualityToolsForBlueJ#50]
# User Story
### Essential components
- [ ] Title describes the story
- [ ] Stakeholder type is identified
- [ ] Outcome is described
- [ ] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story

USER STORY:  As a CS1 student I want to be able to see if I use all the variables that I declare.  I want the tool to point to a line where the unused variable exists.  

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

* _Rule 1_ I want a message that indicates the line number and name/data type of the variable not used
* _Rule 2_ I want the tool to detect and display all unused variables after each compile.

### Scenario 1
**Given**  A variable   
**when**  unused
**then**  extention points to line number of unused variable  

## Supporting Information

https://www.bluej.org/extensions/extensions.html

The PMD Extension for BlueJ is a wrapper for the open-source code analysis utility PMD. This extension gives the BlueJ user a handy way to quickly run the PMD source code analyzer on a Java class in BlueJ. It adds a PMD menu item to the BlueJ class menu. PMD finds common programming flaws like unused variables, empty catch blocks, unnecessary object creation, duplicated code, and so forth. This extension works with any version of PMD and works under Linux or Windows.

After Installation

In BlueJ, open to the main class window that displays your classes, right-click on a class object, when the menu comes up, at the bottom of it you will see PMD as an option, select that and click "check code". A popup will then run PMD against your class source file and then display a popup listing all of the things PMD does not like about your code.

--

# Dependencies
### Depends On
_(Issues on which this story depends)_
### Dependents
_(Issues dependent on this story)_

**Comment by jody** [comment]
Please use the templated form for a user story to ensure that every aspect is addressed.

Please review the intent of Acceptance Criteria, which are a way of testing whether the product satisfies the requirement.

Please use one of the [identified stakeholder types](https://github.com/MetroCS/QualityToolsForBlueJ/blob/master/Vision.md), or explain why a subtype is needed.

It is unclear how this story addresses the intended goals of the project as given in the [Vision Statement](https://github.com/MetroCS/QualityToolsForBlueJ/blob/master/Vision.md); in particular, seeking a **single** extension that **integrates multiple SQA tools**, provides a **cohesive user experience**, and provides a **smooth path for the addition of new SQA tools**.

**Comment by holsappled** [comment]
Closed user story due to no future alteration possibilities.
