### ISSUE TITLE
[UserStory] Clean up developer notes regarding selection of build tool

### ISSUE THREAD

**Issue by jody** [MetroCS/QualityToolsForBlueJ#54]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  _maintainer_  
**I want**  _notes used to help decide among build tools to be archived from the repository_  
**so that**  _the repository is easier to navigate and reflects current status_  

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

* No documentation at the top level of the repository reflects "in process" notes referencing the decision already made to adopt a particular build automation tool

## Supporting Information
_(Relevant information, context, resources)_
* Need to ensure that historical information relevant to project decisions can be accessed in the future.
* There should probably be a more general development convention that no documentation at the top level of the repository reflects "in process" notes referencing decisions that have already been made

### Depends On
_(Issues on which this story depends)_
### Dependents
_(Issues dependent on this story)_

**Comment by henrykgray** [comment]
Please assign @MetroCS/hybrdx to this issue. Thank you.

**Comment by jody** [comment]
Please note that I do not have the ability to assign a "team" to an issue, so will attempt to use a manual and error-prone process to locate and assign appropriate members.

**Comment by henrykgray** [comment]
Ok, all of the team members are correctly assigned. Thank you.
