### ISSUE TITLE
[UserStory] Build Helloworld.java with Gradle

### ISSUE THREAD

**Issue by shadycloud** [MetroCS/QualityToolsForBlueJ#60]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  _Maintainer_  
**I want**  _an initial build environment using Gradle_  
**so that**  _I can confirm the project currently builds and compiles properly._  

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

* _Helloworld.java compiles with build script._ 
* _Scripts allow for future expansion_

## Supporting Information
_(Relevant information, context, resources)_

### Dependents
_[UserStory] Establish project build environment #2_

**Comment by jody** [comment]
Great.  Please work on this!

**Comment by jstrelka** [comment]
Please assign the following github ID's to this tag. Thanks!
@jstrelka 
@shadycloud 
@AustinGailey
@HariShrestha

**Comment by jody** [comment]
Reviewing via PR #61
