### ISSUE TITLE
[UserStory] Connect to a MySQL Database.

### ISSUE THREAD

**Issue by lnieddu** [MetroCS/QualityToolsForBlueJ#64]
# User Story
### Essential components
- [ ] Title describes the story
- [ ] Stakeholder type is identified
- [ ] Outcome is described
- [ ] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
As an Educator,   
I want a basic tutorial for my students showing them how to connect to a MySQL Database using a java program.
 
So, they can learn how to implement an important tool used in DBMS.  

Acceptance Criteria

* A link that gives them a step by step guide on how to download and create a database using the MySQL Shell. 
*The student has access to a blueprint of a method that shows them how to connect to a database. 
* The student connects to a database.

**Comment by jody** [comment]
This doesn't appear to be related to the project.  See: [Vision Statement](https://github.com/MetroCS/QualityToolsForBlueJ/blob/master/Vision.md)
