### ISSUE TITLE
[UserStory] DevelopmentConventions to address full repository structure

### ISSUE THREAD

**Issue by jody** [MetroCS/QualityToolsForBlueJ#65]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  _maintainer_  
**I want**  _an overview of and guide to the entire directory structure of the repository_    
**so that**  _I can appreciate what information is available and locate what I need_  

## Acceptance Criteria

* [DevelopmentConventions.md](../blob/master/DevelopmentConventions.md) elucidates the full repository directory structure (e.g., not just gradle-specific elements)

## Supporting Information
_(Relevant information, context, resources)_

### Depends On
_(Issues on which this story depends)_
### Dependents
_(Issues dependent on this story)_
### Related To
_(Other issues related to this story)_
#8, #54, #62

**Comment by vlazosar** [comment]
Please assign this to @vlazosar
