### ISSUE TITLE
[BUG] package name QualityToolsForBlueJ violates coding convention

### ISSUE THREAD

**Issue by jody** [MetroCS/QualityToolsForBlueJ#66]
**Describe the bug**
The use of package name QualityToolsForBlueJ violates the Java package naming convention
 
**To Reproduce**
1. Verify existence of directory [src/main/java/QualityToolsForBluej](https://github.com/MetroCS/QualityToolsForBlueJ/tree/master/src/main/java/QualityToolsForBlueJ)
2. Review contents of [Library.java](https://github.com/MetroCS/QualityToolsForBlueJ/tree/master/src/main/java/QualityToolsForBlueJ/Library.java)
3. See `package QualityToolsForBlueJ;`

**Expected behavior**
Package names should be all lower case.

**Additional context**
See also: **Naming Conventions** in https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

**Comment by ErDiCooper** [comment]
@ErDiCooper -- Requesting to be assigned this task.

**Comment by jody** [comment]
Addressed via set of PR merges to effect new package name (edu.msudenver.bluejext.qualitytools) and modify the src/ directory structure.
