### ISSUE TITLE
[UserStory] list of user interface technologies

### ISSUE THREAD

**Issue by ccason1** [MetroCS/QualityToolsForBlueJ#67]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
As a maintainer
I want a list of user interface technologies possible for use in this project  
so that I can know what to compare when deciding which technology or technologies to use

## Acceptance Criteria

* I want a list including
  * Name/title of each technology
  * A brief description of the technology
  * Reason(s) why that technology is an appropriate possibility for this project
* The list must be organized and easy to read
* The list must include authoritative references

### Dependents
Issue #15

**Comment by HariShrestha** [comment]
I like to work on this project. I am going to explain about Java fx and Swing  that would be useful for this project as a user interface .

**Comment by babylonianLion** [comment]
I would like to work on this project. I am working on JavaFX at the moment.

**Comment by josevcs2400** [comment]
I would like to contribute to this list as well. I will work on suggesting AWT as an interface technology.
