### ISSUE TITLE
[UserStory] Create UI help file

### ISSUE THREAD

**Issue by alope151** [MetroCS/QualityToolsForBlueJ#69]
# User Story
### Essential components
- [ ] Title describes the story
- [ ] Stakeholder type is identified
- [ ] Outcome is described
- [ ] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  user
**I want**  a help file with steps to teach me how to use the tool 
**so that**  I spend less than 5 minutes learning how to use it.

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

* A set of steps that explain how to successfully select a tool
* A 2-3 sentence description of what each tool does

### Depends On
Issue #32 
### Additional information
The style of the file can change with the state of the project.
Initial style may be limited to just a text (.txt) file

**Comment by jody** [comment]
Why is a "help file" the best way to address the rationale?
This seems like a design/implementation constraint rather than a requirement statement.

**Comment by alope151** [comment]
Issue was redundant and just states what was already said on Issue #32
