### ISSUE TITLE
[UserStory] Undo Function

### ISSUE THREAD

**Issue by mbamiluka** [MetroCS/QualityToolsForBlueJ#72]
# User Story
### Essential components
- [ ] Title describes the story
- [ ] Stakeholder type is identified
- [ ] Outcome is described
- [ ] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  _user  
**I want**  _to be able to reverse errors or unwanted outcomes
**so that**  _so that mistakes are minimal and correctable.  

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

* Undo button or keyboard shortcut is intuitively noticeable
* Undo to a reasonable amount

### Scenario 1
**Given**  a state in which the user wants to reverse an action  
**when**  the user hits undo
**then**  the program will return to the previous state

**Comment by jody** [comment]
It is unclear how this relates to the product, since there is as yet no indication that the extension will make any modifications that would need to be "undone".

Please provide a concrete example that is relevant to this product.

**Comment by jody** [comment]
No recent response.  Considered inactive.
