### ISSUE TITLE
[UserStory] Document Code Convention

### ISSUE THREAD

**Issue by GracchusMinor** [MetroCS/QualityToolsForBlueJ#73]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  maintainer  
**I want**  the code conventions to be accessible through the repository
**so that**  I can reference the selected code conventions of the project

## Acceptance Criteria

* Code convention is documented within the project's repository

### Dependents
["User Story" Document project conventions](https://github.com/MetroCS/QualityToolsForBlueJ/issues/8) #8

**Comment by jody** [comment]
The acceptance criterion appears to be already satisfied. See: (https://github.com/MetroCS/QualityToolsForBlueJ/blob/master/DevelopmentConventions.md#Coding-Convention-Guide)
