### ISSUE TITLE
[UserStory] UI that allows for user defined configuration of BlueJ extensions.

### ISSUE THREAD

**Issue by jstrelka** [MetroCS/QualityToolsForBlueJ#74]
# User Story
### Essential components
- [ ] Title describes the story
- [ ] Stakeholder type is identified
- [ ] Outcome is described
- [ ] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  _user_  
**I want**  _a way to configure any tools that are extensions of BlueJ_  
**so that**  _I can configure extensions of BlueJ to my preferences._  

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

* _Users have a way to configure BlueJ tools to their preferences._
* _Users have a way to import predefined configurations._
* _Users have a way to save configurations._

## Supporting Information
_N/A_

### Depends On
_#43, #38, #33, #3, #2_
### Dependents
_N/A_

**Comment by jody** [comment]
This appears to already exist in the BlueJ product.
See: _Adding items to BlueJ's Preferences panel_ in [Writing BlueJ Extensions](https://www.bluej.org/extensions/writingextensions.html)

**Comment by jstrelka** [comment]
Yes, I believe the BlueJ product only provides a way to select and run the tool. My thought was to have a UI for configuring the tools themselves. Such as turning off specific checks in Checkstyles, etc.
