### ISSUE TITLE
[BUG] "Link" to repository on project website is not live (US #22)

### ISSUE THREAD

**Issue by jody** [MetroCS/QualityToolsForBlueJ#77]
**Describe the bug**
Although the URL to the repository appears on the project website, it is not a "live" link (not clickable).

**To Reproduce**
1. Go to https://metrocs.github.io/QualityToolsForBlueJ/
2. Click on 'https://github.com/MetroCS/QualityToolsForBlueJ'
3. Error is that nothing happens, when it should redirect to the repository

**Expected behavior**
Clicking on the URL text should navigate to the repository.

**Additional context**
See: User Story #22

**Comment by shadycloud** [comment]
I thought this might be an issue. I think the _config.yml file might need to have the line,```     url: https://github.com/MetroCS/QualityToolsForBlueJ ``` added before the link can become live. Example: https://github.com/mmistakes/so-simple-theme/blob/master/example/_config.yml

**Comment by shadycloud** [comment]
![Screen Shot 2019-11-05 at 10 27 22 PM](https://user-images.githubusercontent.com/13189052/68270726-85f89800-001b-11ea-946a-610afda8ee22.png)

**Comment by jody** [comment]
I suggest first checking if it just needs to be entered as an explicit link; that is, using the `[...](...)` syntax to indicate a link.  That's likely to be a more direct fix and appropriately made to the _markdown_ file rather than the _yml_ file.

**Comment by shadycloud** [comment]
Gotcha, will try to fix at lunch if still needed. 

-https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet


![Screen Shot 2019-11-06 at 8 02 44 AM](https://user-images.githubusercontent.com/13189052/68309625-f0392900-006b-11ea-8467-48b894301a95.png)

**Comment by shadycloud** [comment]
![Screen Shot 2019-11-06 at 8 04 22 AM](https://user-images.githubusercontent.com/13189052/68309752-1ced4080-006c-11ea-9dc4-d8a90ca4ccbd.png)

**Comment by shadycloud** [comment]
The line below fixed the link and it can be found in the README.md file. ```
Project Repository: [https://github.com/MetroCS/QualityToolsForBlueJ](https://github.com/MetroCS/QualityToolsForBlueJ) ```
