### ISSUE TITLE
[User Story] Add Code Of Conduct

### ISSUE THREAD

**Issue by SerenaWhite** [MetroCS/QualityToolsForBlueJ#78]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [ ] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  maintainer 
**I want**  a code of conduct
**so that**   there is a clear statement of the project's mission, value, and principles.

## Acceptance Criteria

* Includes information of the project's mission, standards, responsiblities, scope
* How these will be enforced
* Include a link to the project

## Supporting Information
Contributor Covenant: https://www.contributor-covenant.org

Github support: https://help.github.com/en/github/building-a-strong-community/adding-a-code-of-conduct-to-your-project

**Comment by jody** [comment]
This User Story needs a more clear outcome (perhaps linking "code of conduct" to this project) and a review of the acceptance criteria.

**Comment by jody** [comment]
Consider the [following advice](https://help.github.com/en/github/building-a-strong-community/adding-a-code-of-conduct-to-your-project) given by GitHub (**emphasis** mine).

Before adopting a code of conduct for your project:

- Research different codes of conduct designed for open source projects. Choose one that reflects your community's standards.
- **Consider carefully whether _you_ are willing and _able_ to enforce it.**

**Comment by mrayne483** [comment]
I'd like to be added to the  story to work on!

**Comment by mrayne483** [comment]
After researching the types of codes of conduct that are out there, figuring out how I would be able to enforce it seems unclear in the scope of this project...although perhaps it would be more ideal to look into a contributing.md file that would lay out  how people could contribute (ex.  using only specific versions of JDK with the project).

**Comment by jody** [comment]
Addressed by PR #158

**Comment by jody** [comment]
The added code of conduct does not address the project's mission or scope.  It does, however, appear to address "Code of Conduct" expectations, so this particular issue is deemed to be closable.  The project would benefit by having additional contributor information, just not as part of a "Code of Conduct".
