### ISSUE TITLE
[UserStory] User Interface

### ISSUE THREAD

**Issue by HariShrestha** [MetroCS/QualityToolsForBlueJ#85]
# User Story
### Essential components
- [ ] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  maintainer
**I want**  quality tools for converting my .java file into .exe file
**so that**  i can covert my file into executable file.

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

* The tool should convert the .java file into .exe file.

### Scenario 1
**Given**  a clean java file
**when**  its needed 
**then**  the tool should convert the file into executable file.

## Supporting Information
_(Relevant information, context, resources)_

### Depends On
#15 
### Dependents
_(Issues dependent on this story)_

**Comment by jody** [comment]
Title does not describe the story adequately.  Too vague.
The outcome of conversion of .jar to .exe has no obvious relevance with quality assessment.
The rationale appears unrelated to the vision and goals of this project.
