### ISSUE TITLE
[UserStory] User Interface Tutorial for Beginners

### ISSUE THREAD

**Issue by LStCyr** [MetroCS/QualityToolsForBlueJ#86]
# User Story
### Essential components
- [ ] Title describes the story
- [ ] Stakeholder type is identified
- [ ] Outcome is described
- [ ] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  user
**I want**  a guided user interface
**so that**  I can create a project with multiple classes and have it compile and run without errors

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

* Tutorials should be available at the opening of BlueJ
* The tutorials and guides should begin by covering the editor basics such as navigating, creating a new class, and how the inheritance arrow works 
* Display should look professional. Not busy or overstimulating for a new student

### Scenario 1
**Given**  a student who has never written a java program
**when**  correctly following the steps presented in the tutorials
**then**  they can build their first "Hello World" in less than a half an hour.

**Given**  a student who has never written a java program
**when**  incorrectly following the tutorial's instructions
**then**  they are told how to correct their mistake and are given the opportunity to try and submit their code until they get it right.

## Supporting Information
There are a lot of products that provide tutorials for new programmers, but the best one's I have utilized have been integrated with the IDE itself. The goal for this ticket is to provide a new programmer with a high quality guide that improves the quality of their understanding of the interface of an IDE. 

### Depends On
_(Issues on which this story depends)_
### Dependents
_(Issues dependent on this story)_

**Comment by jody** [comment]
This project concerns development of a quality tools extension for BlueJ, thus this user story is not relevant.  In addition, the BlueJ product includes an interactive tutorial, so the user story is already satisfied.
