### ISSUE TITLE
[UserStory] Tutorial to Customizing BlueJ Environment

### ISSUE THREAD

**Issue by LStCyr** [MetroCS/QualityToolsForBlueJ#87]
# User Story
### Essential components
- [ ] Title describes the story
- [ ] Stakeholder type is identified
- [ ] Outcome is described
- [ ] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  user
**I want**  a guide to the various configurations and appearances available for BlueJ
**so that**  I can find an interface that suits my preferences and environment

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

* _Rule 1_ The tutorial should appear upon opening BlueJ unless otherwise specified
* _Rule 2_ The tutorial should be a step-by-step guide to changing my preferences including appearance and behavior, accessibility, and UI options
* _Rule 3_ The tutorial should display basic instructions on how to make custom change that are outside of the scope of a pre-built theme

### Scenario 1
**Given**  a new user wants to explore what options exist for the themes and appearances of BlueJ
**when**  they follow the tutorial 
**then**  the user can customize the experience without having to seek support or have questions answered online.

## Supporting Information
_(Relevant information, context, resources)_

### Depends On
_(Issues on which this story depends)_
### Dependents
_(Issues dependent on this story)_

**Comment by jody** [comment]
This is outside the scope of addressing the goals of the Quality Tools for BlueJ project.
