### ISSUE TITLE
[UserStory] brief identification of the user story

### ISSUE THREAD

**Issue by ppanth7** [MetroCS/QualityToolsForBlueJ#90]
# User Story
### Essential components
- [ ] Title describes the story
- [ ] Stakeholder type is identified
- [ ] Outcome is described
- [ ] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
As a maintainer 
I want a YouTube tutorial with audio and subtitle on each user interface technologies possible for use in this project 
so that the instructions are ADA compliant and anyone with disability can know how to utilize  technologies provided

## Acceptance Criteria

* I want a list including name/title of each technology
* when clicked on the name opens the respective tutorials.
* The tutorial gives a :
         1.  I want a list including name/title of each technology
         2. A brief description of the technology
         3. Reason(s) why that technology is an appropriate possibility for this project
         4. how to utilize the technology

### Dependents
Issue #15

**Comment by jody** [comment]
Title fails as essential component.
The need for any video is not validated.
Requiring YouTube seems overly restrictive.
