### ISSUE TITLE
[UserStory]User Interface

### ISSUE THREAD

**Issue by HariShrestha** [MetroCS/QualityToolsForBlueJ#91]
# User Story
### Essential components
- [ ] Title describes the story
- [x] Stakeholder type is identified
- [ ] Outcome is described
- [ ] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  maintainer 
**I want**  quality tool which shows as a menu in blue j
**so that**  i can use it for cleaning and packaging of my file.

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

The tool should shows clearly so that i can use it easily.
### Scenario 1
**Given**  a bad codes file
**when**  i click the tool 
**then**  it should clean and package the file.

## Supporting Information
_(Relevant information, context, resources)_

## Dependencies
#15 
_(Issues on which this story depends)_
### Dependents
_(Issues dependent on this story)_

**Comment by jody** [comment]
Title is ambiguous.
This appears to be a design or implementation constraint rather than a requirement.
Why is a "menu item" the best user interface choice?
How is "packaging" related to this product or this product's menu item?

**Comment by jody** [comment]
No recent response.  Closing issue.
