### ISSUE TITLE
[UserStory] UI Visual Examples

### ISSUE THREAD

**Issue by corywilson88** [MetroCS/QualityToolsForBlueJ#94]
# User Story
### Essential components
- [ ] Title describes the story
- [ ] Stakeholder type is identified
- [ ] Outcome is described
- [ ] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  maintainer 
**I want**  a wireframe diagram for an extension that has been added to BlueJ via a menu item or to the preference panel  
**so that**  I can visually have a skeleton on how to implement a BlueJ extension.

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

* Must visually represent the addition of an extension added to BlueJ
* Ensure that the location of the preference panel and menus are explicitly identified and labeled
* Finding the BlueJ extension that is to be added is easily found and recognized

### Depends On
#15 
#67

**Comment by jody** [comment]
Please rewrite Acceptance Criteria to include **all** necessary criteria.

**Comment by jody** [comment]
No recent response. Closing issue.
