### ISSUE TITLE
[UserStory] Tutorial of a basic intuitive UI

### ISSUE THREAD

**Issue by lnieddu** [MetroCS/QualityToolsForBlueJ#95]
# User Story
### Essential components
- [ ] Title describes the story
- [ ] Stakeholder type is identified
- [ ] Outcome is described
- [ ] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
As a user_  
I want a brief tutorial of what an intuitive UI looks like 
so that I can better understand the essential of a intuitive UI 

## Acceptance Criteria
Tutorial is brief but informative 
Explains the essentials of an intuitive UI

## Supporting Information
_(Relevant information, context, resources)_

### Depends On
Issue number 15

**Comment by jody** [comment]
Many of these already exist.  What is the actual product/project requirement?
