### ISSUE TITLE
[UserStory] A Reference List for Accessing Tools

### ISSUE THREAD

**Issue by ErDiCooper** [MetroCS/QualityToolsForBlueJ#96]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  maintainer
**I want**  a reference list for accessing each tool planned for implementation.
**so that**  I and others can quickly and easily access them during development.

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

* Describes how to access each tool planned for implementation.
* For each tool, tells whether or not it is a bluej extension. (If not, what?)

### Scenario 1
**Given** a maintainer wants to work on the implementation of an unfamiliar tool,
**when** they look up said tool in the reference list,
**then** the will know how to access said tool to learn what it must do.

## Supporting Information
[toolsForIntegration.md](https://github.com/MetroCS/QualityToolsForBlueJ/blob/master/toolsForIntegration.md)

### Depends On
_(Issues on which this story depends)_
### Dependents
_(Issues dependent on this story)_

**Comment by jody** [comment]
Confusing use of term, "tool".  Please make less ambiguous by clarifying intended meaning.  For example, to my understanding "quality assessment tool" and "BlueJ extension" are distinct and do not overlap.

As far as I can tell, this user story is already addressed by the toolsForIntegration.md given as Supporting Information.

Please indicate more clearly what is intended and how the outcome is to be measured.

**Comment by jody** [comment]
No recent response.  Closing issue.
