### ISSUE TITLE
[UserStory] Add information to build environment section of Development Conventions

### ISSUE THREAD

**Issue by henrykgray** [MetroCS/QualityToolsForBlueJ#97]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a** Developer  
**I want** DevelopmentConventions.md to contain an overview and links of each build tool we are using
**so that** I can easily find information about each tool we are using

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

* The Build Environment section of [DevelopmentConventions.md](../blob/master/DevelopmentConventions.md) contains an overview and links to the homepage of each tool
* There are no ToDos in the Build Environment section of DevelopmentConventions.md

## Supporting Information
[toolsForIntegration.md](../blob/master/toolsForIntegration.md) contains overviews and links to some QA and build tools

### Depends On
_(Issues on which this story depends)_
### Dependents
_User Stories: #2, #5, #8 _

**Comment by henrykgray** [comment]
please assign 
@henrykgray
@yadhikar 
@Bitked 
@MaTTerCuBe 
to this issue please.

**Comment by jody** [comment]
See updated User Story text.
